[package]
name = "hello"
version = "0.1.0"
authors = ["Salvador Gudino <s3chn1x@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
